Turn fil-deal-ingestor into automated service
filecoin-station/fil-deal-ingester pull request #26
Opened 2024-12-27 10:31 UTC by pyropy

- Add dockerfile and fly config
- Refactor run script to support running from docker container
- Update .gitignore and add .dockerignore files

2025-01-06 10:49 UTC, juliangruber commented
@pyropy why is this a draft?

2025-01-06 13:06 UTC, bajtos requested changes
Nice! The change looks great at the high level; let's improve a couple of details now.

2025-01-07 06:27 UTC, pyropy commented on README.md
> +```
Certainly!

2025-01-07 06:30 UTC, pyropy commented
> @pyropy why is this a draft?

Woops, I think I forgot to switch it from draft. 👀

2025-01-07 06:40 UTC, pyropy commented on README.md
> +```
We can run updates on existing machine without creating new one or removing the existing one. In order to that we can run `fly machine update <machine-id>`. I also added new subsection for updating existing machine to the README.

2025-01-07 13:18 UTC, juliangruber commented on README.md
> +**NOTE: Make sure you have the fly.io CLI installed and logged in.**
```suggestion
**NOTE: Make sure you have the fly.io CLI installed and are logged in.**
```

2025-01-07 13:19 UTC, juliangruber commented on README.md
> +```
```suggestion
### One-time setup

Set up an app, volume and secrets:

```sh
fly apps create --name=fil-deal-ingester --org=<org-name>
fly volumes create fil_deal_ingester_data --size=80 --app=fil-deal-ingester --region=<region> --snapshot-retention=1
fly secrets set DATABASE_URL=<postgres-connection-string> --app=fil-deal-ingester
fly secrets set SLACK_WEBHOOK_URL=<slack-webhook-url> --app=fil-deal-ingester
```
```

2025-01-07 13:41 UTC, bajtos commented on README.md
> +```
I'd like to preserve the information that _Creating scheduled machine has to be done by hand as it's not possible to set up a schedule inside the `fly.toml` file._

2025-01-07 13:44 UTC, bajtos commented on run.sh
> +fi
Let's always print the summary to stdout, it will make it easier for us to find this information when inspecting logs in papertrail.

```suggestion
echo $MESSAGE

if [ -n "$SLACK_WEBHOOK_URL" ]; then
  echo "** Sending message to slack **"
  curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
fi
```

2025-01-08 09:11 UTC, bajtos commented
I need to land this PR to continue my work on https://github.com/filecoin-station/fil-deal-ingester/pull/30, so I merged the suggested documentation improvements.

@juliangruber LGTY now?

2025-01-08 09:12 UTC, bajtos commented on README.md
> +
Missing end of the code block.

````suggestion
fly secrets set SLACK_WEBHOOK_URL=<slack-webhook-url> --app=fil-deal-ingester
```

````

2025-01-08 09:13 UTC, bajtos approved these changes

2025-01-08 12:55 UTC, juliangruber approved these changes
@bajtos lgtm!

2025-01-08 12:56 UTC, merged